trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  SampleVariable01: "Some sample content"
  
steps:
- pwsh: |
    Write-Host "SampleVariable01: $(SampleVariable01)"
  displayName: "Show a normal plain text variable"

- pwsh: |
    Write-Host "SampleVariable01 by ENV: $Env:SAMPLEENVVARIABLE"
  env: 
    SAMPLEENVVARIABLE: $(SampleVariable01)
  displayName: "Show a normal plain text variable by ENV"

- pwsh: |
    Write-Host "SecretVariable01: $(SecretVariable01)"
  displayName: "Show a secret variable inline"

- pwsh: |
    dir env:
  displayName: "Show all environment variables"

- pwsh: |
    Write-Host "SampleVariable01 by ENV: $Env:SECRETENVVARIABLE"
  env: 
    SECRETENVVARIABLE: $(SecretVariable01)
  displayName: "Show a secret variable inline by ENV"

- pwsh: |
    $output = ($Env:SECRETENVVARIABLE -split "(\S)") -join " "
    Write-Host "SampleVariable01 by ENV: $($output)"
  env: 
    SECRETENVVARIABLE: $(SecretVariable01)
  displayName: "Work with secret variables"