trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  - name: SampleVariable01
    value: "Some sample content"
  - group: DemoVariableGroup
  - group: DemoKeyVaultVariableGroup
  
steps:
- pwsh: |
    Write-Host "SampleVariable01: $(SampleVariable01)"
  displayName: "Show a plain text variable"

- pwsh: |
    Write-Host "GroupValue1: $(GroupValue1)"
  displayName: "Show a plain text variable from group"

- pwsh: |
    Write-Host "GroupSecret1: $(GroupSecret1)"
  displayName: "Show a secret variable from group"

- pwsh: |
    Write-Host "theSecret: $(theSecret)"
  displayName: "Show a secret variable from Key Vault by group"
